var userName;
var titleText;
var dateTime;
var textArea;
var img;
var imgTitle;

function obterElementos(){
	
	userName = document.getElementById('user').innerHTML;
	titleText = document.getElementById('title').innerHTML;
	dateTime = document.getElementById('dateTime').innerHTML;
	textArea = document.getElementById('textArea').innerHTML;
	img = document.getElementById('img').innerHTML;
	imgTitle = document.getElementById('imgTitle').innerHTML;

}

function gerarPagina(){
	var meta1=document.createElement('meta');
	meta1.setAttribute('charset','utf-8');
	var meta2=ce('meta','viewport');
	meta2.setAttribute('content','width=device-width, initial-scale=1.0');
	var meta3=ce('meta','description');
	var meta4=ce('meta','author');
	var title1=document.createElement('title');
	var txt6=document.createTextNode('Notícia Padrão - Ufal - Ciência da Computação');
	title1.appendChild(txt6);
	var link1=document.createElement('link');
	link1.setAttribute('href','css/bootstrap.min.css');
	link1.setAttribute('rel','stylesheet');
	var link2=document.createElement('link');
	link2.setAttribute('href','css/animate.min.css');
	link2.setAttribute('rel','stylesheet');
	var link3=document.createElement('link');
	link3.setAttribute('href','css/font-awesome.min.css');
	link3.setAttribute('rel','stylesheet');
	var link4=document.createElement('link');
	link4.setAttribute('href','css/lightbox.css');
	link4.setAttribute('rel','stylesheet');
	var link5=document.createElement('link');
	link5.setAttribute('href','css/main.css');
	link5.setAttribute('rel','stylesheet');
	var link6=document.createElement('link');
	link6.setAttribute('id','css-preset');
	link6.setAttribute('href','css/presets/preset1.css');
	link6.setAttribute('rel','stylesheet');
	var link7=document.createElement('link');
	link7.setAttribute('href','css/responsive.css');
	link7.setAttribute('rel','stylesheet');
	var link8=document.createElement('link');
	link8.setAttribute('href','css/login.css');
	link8.setAttribute('rel','stylesheet');
	var link9=document.createElement('link');
	link9.setAttribute('href','css/card.css');
	link9.setAttribute('rel','stylesheet');
	var link10=document.createElement('link');
	link10.setAttribute('href','http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700');
	link10.setAttribute('rel','stylesheet');
	link10.setAttribute('type','text/css');
	var link11=document.createElement('link');
	link11.setAttribute('rel','shortcut icon');
	link11.setAttribute('href','images/logo_cc.gif');
	var div1=document.createElement('div');
	div1.className='preloader';
	var i1=document.createElement('i');
	i1.className='fa fa-circle-o-notch fa-spin';
	div1.appendChild(i1);
	var header1=document.createElement('header');
	header1.setAttribute('id','home');
	var div2=document.createElement('div');
	div2.className='main-nav';
	header1.appendChild(div2);
	var div3=document.createElement('div');
	div3.className='container';
	div2.appendChild(div3);
	var div4=document.createElement('div');
	div4.className='navbar-header';
	div3.appendChild(div4);
	var button1=document.createElement('button');
	button1.setAttribute('type','button');
	button1.className='navbar-toggle';
	button1.setAttribute('data-toggle','collapse');
	button1.setAttribute('data-target','.navbar-collapse');
	div4.appendChild(button1);
	var span1=document.createElement('span');
	span1.className='sr-only';
	button1.appendChild(span1);
	var txt34=document.createTextNode('Toggle navigation');
	span1.appendChild(txt34);
	var span2=document.createElement('span');
	span2.className='icon-bar';
	button1.appendChild(span2);
	var span3=document.createElement('span');
	span3.className='icon-bar';
	button1.appendChild(span3);
	var span4=document.createElement('span');
	span4.className='icon-bar';
	button1.appendChild(span4);
	var a1=document.createElement('a');
	a1.className='navbar-brand';
	a1.setAttribute('href','index.html');
	div4.appendChild(a1);
	var h11=document.createElement('h1');
	a1.appendChild(h11);
	var img1=document.createElement('img');
	img1.className='img-responsive';
	img1.setAttribute('src','images/logo.png');
	img1.setAttribute('alt','logo');
	h11.appendChild(img1);
	var div5=document.createElement('div');
	div5.className='collapse navbar-collapse';
	div3.appendChild(div5);
	var ul1=document.createElement('ul');
	ul1.className='nav navbar-nav navbar-right';
	div5.appendChild(ul1);
	var li1=document.createElement('li');
	li1.className='scroll ';
	ul1.appendChild(li1);
	var a2=document.createElement('a');
	a2.setAttribute('href','index.html');
	li1.appendChild(a2);
	var txt46=document.createTextNode('Home');
	a2.appendChild(txt46);
	header1.appendChild(txt51);
	var section1=document.createElement('section');
	section1.setAttribute('id','about-us');
	section1.className='parallax';
	var div6=document.createElement('div');
	div6.className='container';
	section1.appendChild(div6);
	var div7=document.createElement('div');
	div7.className='row';
	div6.appendChild(div7);
	var div8=document.createElement('div');
	div8.className='col-sm-12>\n          <div class=';
	div8.setAttribute('data-wow-duration','1000ms');
	div8.setAttribute('data-wow-delay','300ms');
	div7.appendChild(div8);
	var div9=document.createElement('div');
	div9.className='col-sm-6';
	div6.appendChild(div9);
	var div10=document.createElement('div');
	div10.className='text-justify about-info wow fadeInUp';
	div10.setAttribute('data-wow-duration','1000ms');
	div10.setAttribute('data-wow-delay','300ms');
	div9.appendChild(div10);
	var div11=document.createElement('div');
	div11.className='container';
	div9.appendChild(div11);
	var h21=document.createElement('h2');
	div11.appendChild(h21);
	var txt65=document.createTextNode('Título');
	h21.appendChild(txt65);
	var p1=document.createElement('p');
	p1.className='text-justify';
	div11.appendChild(p1);
	var txt67=document.createTextNode('Autor');
	p1.appendChild(txt67);
	var p2=document.createElement('p');
	p2.className='text-justify';
	div11.appendChild(p2);
	var txt69=document.createTextNode('Data e Hora');
	p2.appendChild(txt69);
	var p3=document.createElement('p');
	p3.className='text-justify col-sm-7';
	div11.appendChild(p3);
	var txt71=document.createTextNode('Preparem-se para a encrenca!');
	p3.appendChild(txt71);
	var br1=document.createElement('br');
	p3.appendChild(br1);
	var txt72=document.createTextNode('Encrenca em dobro!');
	p3.appendChild(txt72);
	var br2=document.createElement('br');
	p3.appendChild(br2);
	var txt73=document.createTextNode('Para proteger o mundo da devastação!');
	p3.appendChild(txt73);
	var br3=document.createElement('br');
	p3.appendChild(br3);
	var txt74=document.createTextNode('Para unir todas as pessoas de nossa nação!');
	p3.appendChild(txt74);
	var br4=document.createElement('br');
	p3.appendChild(br4);
	var txt75=document.createTextNode('Para denunciar os males da verdade e do amor!');
	p3.appendChild(txt75);
	var br5=document.createElement('br');
	p3.appendChild(br5);
	var txt76=document.createTextNode('Para estender o nosso poder às estrelas!');
	p3.appendChild(txt76);
	var br6=document.createElement('br');
	p3.appendChild(br6);
	var txt77=document.createTextNode('Jesse!');
	p3.appendChild(txt77);
	var br7=document.createElement('br');
	p3.appendChild(br7);
	var txt78=document.createTextNode('James!');
	p3.appendChild(txt78);
	var br8=document.createElement('br');
	p3.appendChild(br8);
	var txt79=document.createTextNode('Equipe Rocket decolando na velocidade da luz!');
	p3.appendChild(txt79);
	var br9=document.createElement('br');
	p3.appendChild(br9);
	var txt80=document.createTextNode('Renda-se agora ou preparem-se');
	p3.appendChild(txt80);
	var br10=document.createElement('br');
	p3.appendChild(br10);
	var txt81=document.createTextNode('Para lutar!');
	p3.appendChild(txt81);
	var br11=document.createElement('br');
	p3.appendChild(br11);
	var div12=document.createElement('div');
	div12.className='col-sm-6 col-md-4 col-lg-3 mt-4';
	div11.appendChild(div12);
	var div13=document.createElement('div');
	div13.style.marginTop="-100px";
	div12.appendChild(div13);
	var div14=document.createElement('div');
	div14.className='card';
	div12.appendChild(div14);
	var span5=document.createElement('span');
	span5.className='folio-expand';
	div14.appendChild(span5);
	var a3=document.createElement('a');
	a3.setAttribute('href','images/batman.jpg');
	a3.setAttribute('data-lightbox','portfolio');
	span5.appendChild(a3);
	var img2=document.createElement('img');
	img2.className='card-img-top';
	img2.setAttribute('src','images/batman.jpg');
	a3.appendChild(img2);
	var div15=document.createElement('div');
	div15.className='card-block';
	div14.appendChild(div15);
	var h51=document.createElement('h5');
	h51.className='text-bold';
	div15.appendChild(h51);
	var txt89=document.createTextNode('Título da Imagem');
	h51.appendChild(txt89);
	var footer1=document.createElement('footer');
	footer1.setAttribute('id','footer');
	var div16=document.createElement('div');
	div16.className='footer-top wow fadeInUp';
	div16.setAttribute('data-wow-duration','1000ms');
	div16.setAttribute('data-wow-delay','300ms');
	footer1.appendChild(div16);
	var div17=document.createElement('div');
	div17.className='container text-center';
	div16.appendChild(div17);
	var div18=document.createElement('div');
	div18.className='footer-logo';
	div17.appendChild(div18);
	var a4=document.createElement('a');
	a4.setAttribute('href','index.html');
	div18.appendChild(a4);
	var img3=document.createElement('img');
	img3.className='img-responsive';
	img3.setAttribute('src','images/logo.png');
	a4.appendChild(img3);
	var div19=document.createElement('div');
	div19.className='social-icons';
	div17.appendChild(div19);
	var ul2=document.createElement('ul');
	div19.appendChild(ul2);
	var li2=document.createElement('li');
	ul2.appendChild(li2);
	var a5=document.createElement('a');
	a5.className='envelope';
	a5.setAttribute('href','#');
	li2.appendChild(a5);
	var i2=document.createElement('i');
	i2.className='fa fa-envelope';
	a5.appendChild(i2);
	var li3=document.createElement('li');
	ul2.appendChild(li3);
	var a6=document.createElement('a');
	a6.className='twitter';
	a6.setAttribute('href','#');
	li3.appendChild(a6);
	var i3=document.createElement('i');
	i3.className='fa fa-twitter';
	a6.appendChild(i3);
	var li4=document.createElement('li');
	ul2.appendChild(li4);
	var a7=document.createElement('a');
	a7.className='dribbble';
	a7.setAttribute('href','#');
	li4.appendChild(a7);
	var i4=document.createElement('i');
	i4.className='fa fa-dribbble';
	a7.appendChild(i4);
	var li5=document.createElement('li');
	ul2.appendChild(li5);
	var a8=document.createElement('a');
	a8.className='facebook';
	a8.setAttribute('href','#');
	li5.appendChild(a8);
	var i5=document.createElement('i');
	i5.className='fa fa-facebook';
	a8.appendChild(i5);
	var li6=document.createElement('li');
	ul2.appendChild(li6);
	var a9=document.createElement('a');
	a9.className='linkedin';
	a9.setAttribute('href','#');
	li6.appendChild(a9);
	var i6=document.createElement('i');
	i6.className='fa fa-linkedin';
	a9.appendChild(i6);
	var li7=document.createElement('li');
	ul2.appendChild(li7);
	var a10=document.createElement('a');
	a10.className='tumblr';
	a10.setAttribute('href','#');
	li7.appendChild(a10);
	var i7=document.createElement('i');
	i7.className='fa fa-tumblr-square';
	a10.appendChild(i7);
	var script1=document.createElement('script');
	script1.setAttribute('type','text/javascript');
	script1.setAttribute('src','js/jquery.js');
	var script2=document.createElement('script');
	script2.setAttribute('type','text/javascript');
	script2.setAttribute('src','js/bootstrap.min.js');
	var script3=document.createElement('script');
	script3.setAttribute('type','text/javascript');
	script3.setAttribute('src','http://maps.google.com/maps/api/js?sensor=true');
	var script4=document.createElement('script');
	script4.setAttribute('type','text/javascript');
	script4.setAttribute('src','js/jquery.inview.min.js');
	var script5=document.createElement('script');
	script5.setAttribute('type','text/javascript');
	script5.setAttribute('src','js/wow.min.js');
	var script6=document.createElement('script');
	script6.setAttribute('type','text/javascript');
	script6.setAttribute('src','js/mousescroll.js');
	var script7=document.createElement('script');
	script7.setAttribute('type','text/javascript');
	script7.setAttribute('src','js/smoothscroll.js');
	var script8=document.createElement('script');
	script8.setAttribute('type','text/javascript');
	script8.setAttribute('src','js/jquery.countTo.js');
	var script9=document.createElement('script');
	script9.setAttribute('type','text/javascript');
	script9.setAttribute('src','js/lightbox.min.js');
	var script10=document.createElement('script');
	script10.setAttribute('type','text/javascript');
	script10.setAttribute('src','js/main.js');
}